### ISSUE TITLE
Make the table searchable and sortable

### ISSUE THREAD

**Issue by moredatapls** [xr-muc/co2clock#12]
Make the table with the countries searchable and sortable by the features. Also, put the "world" entry at the top

**Comment by natstar93** [comment]
Hi, I've started work on making the table sortable. Not finished yet but what I've done so far is on a [branch of my fork](https://github.com/xr-muc/co2clock/compare/master...natstar93:order-by-total-budget?expand=1). Needs some tidying up style wise and implementing for the other categories. I had to change the emissions object to an array to sort things easily so have just got a small array containing a few countries for now - will write a script to change the whole object soon.

Screenshot of how it looks so far:

<img width="1066" alt="Screenshot 2019-10-29 at 23 01 01" src="https://user-images.githubusercontent.com/10135250/67815905-2a209300-faa0-11e9-8354-8a7189899d76.png">

**Comment by natstar93** [comment]
If you could assign me to this issue that would be great

**Comment by moredatapls** [comment]
Looks cool! Assigned you

**Comment by moredatapls** [comment]
Sweet, #14 made it sortable, now a search functionality would be great as well.

**Comment by natstar93** [comment]
It's coming along! Still a bit of finishing off to do, hopefully tomorrow evening

<img width="1136" alt="Screenshot 2019-11-11 at 23 05 37" src="https://user-images.githubusercontent.com/10135250/68628272-0154c080-04d8-11ea-82d2-ffa431cb9f29.png">
