### ISSUE TITLE
Promote project on 24 Pull Requests

### ISSUE THREAD

**Issue by natstar93** [xr-muc/co2clock#15]
Get project promoted on [24 Pull Requests](https://24pullrequests.com) to attract more contributors!

- How do we get the project listed?
- Do they have a tagging system, similar to [Hacktoberfest](https://hacktoberfest.digitalocean.com)?

**Comment by moredatapls** [comment]
Submitted it [here](https://24pullrequests.com/projects/new), I suppose they manually add it to their list. Thanks for the recommendation, let's hope that they accept it.
