### ISSUE TITLE
The menu should refer to the blocks, not other links

### ISSUE THREAD

**Issue by moredatapls** [xr-muc/co2clock#5]
The menu should be collapsed by default and link to the blocks on the page

**Comment by lkreimann** [comment]
I don't think a collapsed menu is a good idea for the desktop/full-screen view. Bootstrap collapses the menu for smaller screens anyway. 
I guess there are probably more accessibility problems, when you collapse a menu per default (not a pro in this field though).
Just leaving my thoughts. Really like the site :grin:

**Comment by moredatapls** [comment]
Thanks @lkreimann for the feedback, you're right!

**Comment by moredatapls** [comment]
Closed by #8
